- hosts: drupal_servers
  become: yes
  vars:
    drupal_compose_state: present
    mariadb_version: "11.1"
    # nginx_user: "not_admin"
    # nginx_password: "not_admin"
    compose_project_path: "/home/{{ ansible_user }}/projects/project/containers"
  roles:
    - drupal_deploy